### ISSUE TITLE
Small typo 

### ISSUE THREAD

**Issue by hacks2learn** [UltimateHackers/AwesomeXSS#11]
Hello @s0md3v 

Great work and thanks for all your contributions!  Just happened to be looking at the `Awesome Encoding` table and noticed a typo in the Char column for backslash `\` ... you actually have a forward slash `/`.

 HTML | Char | Numeric | Description | Hex | CSS (ISO) | JS (Octal) | URL 
 -- | -- | -- | -- | -- | -- | -- | -- 
 -- | -- | -- | -- | -- | -- | -- | -- 
 `&bsol;` | ~~/~~ | `&#92;` | backslash | `u+005C` | `\005c` | \134 | %5C 
 -- | ^here | -- | -- | -- | -- | -- | -- 
 -- | -- | -- | -- | -- | -- | -- | -- 
 `&bsol;` | \ | `&#92;` | backslash | `u+005C` | `\005c` | \134 | %5C 
 -- | -- | -- | -- | -- | -- | -- | --

**Comment by blockchainguard** [comment]
<script>([,ウ,,,,ア]=[]+{},[ネ,ホ,ヌ,セ,,ミ,ハ,ヘ,,,
ナ]=[!!ウ]+!ウ+ウ.ウ)[ア+=ウ+ナ+ヘ+ネ+ホ+ヌ+
ア+ネ+ウ+ホ][ア](ミ+ハ+セ+ホ+ネ+'(-~ウ)')()</script>

**Comment by 1234567-glitch** [comment]
Hi and how are you to you all. thanks for well coming me to coding i am still learning. johannesburg south africa. Brian
