### ISSUE TITLE
use // to close a tag instead of >

### ISSUE THREAD

**Issue by Ppsoft1991** [UltimateHackers/AwesomeXSS#3]
Hello,In your tricks "

> you can use // to close a tag instead of >

."，I tried it in chrome,but its not worked,It's specific browser or version?

**Comment by s0md3v** [comment]
There must be a `>` somewhere later in the code.
For example, the following works
```html
<body>
<svg onload=alert()//
<span>This works</span>
</body>
```

While this one doesn't
```html
<span>Doesn't work</span>
<svg onload=alert()//
```
