### ISSUE TITLE
Can this be made to be foldable?

### ISSUE THREAD

**Issue by m4dh47** [UltimateHackers/AwesomeXSS#9]
Can this be made to close and open along given paths so it can be more user friendly? Similar to the [OSINT Framework](https://osintframework.com/). It could even be an alternate version offered...

**Comment by 1234567-glitch** [comment]
@m4dh47 hi, can i work on this issue?

**Comment by s0md3v** [comment]
This doesn't align with the vision of this project, thanks for the suggestion tho.
